### ISSUE TITLE
페이지 갱신이 안됩니다.

### ISSUE THREAD

**Issue by akaksms** [meeeejin/srtmacro#2]
프로그램이 페이지 갱신을 하지 못하면서 정상적으로 작동하지 않는 것으로 보입니다.
수정이 필요한 것 같습니다. 감사합니다.

**Comment by meeeejin** [comment]
혹시 어떤 상황에서 페이지 갱신을 못하는지 알 수 있을까요? 제 크롬에서는 정상 작동해서 문제 상황을 명확히 파악하지 못하고 있습니다. 감사합니다.

**Comment by akaksms** [comment]
헉 죄송합니다. 이제야 봤네요...
오늘 사용해 보니 다시 정상적으로 작동했습니다. 앱이 아니고 다른 문제였나 싶네요
좋은 앱 감사합니다.

**Comment by akaksms** [comment]
내일 닫겠습니다. 늦게 봐서 죄송합니다..^^;;
