### ISSUE TITLE
SRT매크로는 더이상 안되는건가요?

### ISSUE THREAD

**Issue by djit3** [meeeejin/srtmacro#8]
너무 너무 궁금합니다.

**Comment by meeeejin** [comment]
안녕하세요.
SRT Macro 확장 프로그램에 관심을 가져주셔서 감사합니다.

아시다시피, 현재 SRT Macro 확장 프로그램은 악용 방지 및 SR 측의 요청으로 크롬 및 웨일 확장프로그램 게시를 중단한 상태입니다.

기타 문의 사항은 meeeeejin@gmail.com 로 메일 부탁드립니다.

감사합니다.
